### ISSUE TITLE
Camera flip function doesn't work

### ISSUE THREAD

**Issue by asherworld** [SimCoderYoutube/InstagramClone#14]
From Add.js

Everything works good. exception the flip feature.

when I set the camera flip function to TouchableOpacity. It works as well.
but if I change from TouchableOpacity to Button, it doesn't work to flip the camera. 

I double checked the code by copy and paste your code.
but  it still doesn't work

**Comment by SimCoderYoutube** [comment]
Hi!

Does any error log appear when you click the button?

**Comment by asherworld** [comment]
Nope error message doesn't appear

**Comment by SimCoderYoutube** [comment]
Alright, Could you please let me know what device you are testing this on? When you set the type variable to Camera.Constants.Type.front does it automatically set the camera to the front camera?

like so:
` const [type, setType] = useState(Camera.Constants.Type.front);`
