### ISSUE TITLE
Firebase bandwidth

### ISSUE THREAD

**Issue by jorgeorejas** [SimCoderYoutube/InstagramClone#26]
I'm trying to show Videos in the feed and there is some troubles with the Firebase Bandwidth, is there something I could check or did I miss any step?

**Comment by successfullbussinessman** [comment]
"some troubles with the Firebase Bandwidth" Can you elaborate?

**Comment by jorgeorejas** [comment]
I will close this issue, the problem was solved, it was caused by a typo. Thank you.
