### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExponentFileSystem')

### ISSUE THREAD

**Issue by AAGAM17** [SimCoderYoutube/InstagramClone#34]

**Comment by QasidLabeed** [comment]
Also facing the same issue here

**Comment by YosubShin** [comment]
This happened me as well and I think it was due to not specifying the versions of some of the "expo-*" packages and `npm install` implicitly chooses to install a newer incompatible version.

My build works after adding following two lines to `frontend/package.json`:

```
diff --git a/frontend/package.json b/frontend/package.json
index 7fd3bc3f..68abfd3d 100644
--- a/frontend/package.json
+++ b/frontend/package.json
@@ -25,6 +25,8 @@
     "expo-camera": "~11.2.2",
     "expo-cameraroll": "^1.1.0",
     "expo-checkbox": "^1.0.3",
+    "expo-constants": "11.0.2",
+    "expo-crypto": "9.2.0",
     "expo-device": "~3.3.0",
     "expo-image-picker": "~10.2.2",
     "expo-linear-gradient": "~9.2.0",
```

**Comment by AAGAM17** [comment]
> This happened me as well and I think it was due to not specifying the versions of some of the "expo-*" packages and `npm install` implicitly chooses to install a newer incompatible version.
> 
> My build works after adding following two lines to `frontend/package.json`:
> 
> ```
> diff --git a/frontend/package.json b/frontend/package.json
> index 7fd3bc3f..68abfd3d 100644
> --- a/frontend/package.json
> +++ b/frontend/package.json
> @@ -25,6 +25,8 @@
>      "expo-camera": "~11.2.2",
>      "expo-cameraroll": "^1.1.0",
>      "expo-checkbox": "^1.0.3",
> +    "expo-constants": "11.0.2",
> +    "expo-crypto": "9.2.0",
>      "expo-device": "~3.3.0",
>      "expo-image-picker": "~10.2.2",
>      "expo-linear-gradient": "~9.2.0",
> ```

Thanks Solved
