### ISSUE TITLE
Error: ENOENT: no such file or directory frontend/google-services.json

### ISSUE THREAD

**Issue by lsantella** [SimCoderYoutube/InstagramClone#35]
When trying to run expo start -c from the frontend folder i get this issue. Which is stemming from not being able to find the googleServicesFile in the app.json under android and apple

**Comment by SimCoderYoutube** [comment]
Hi @lsantella !

You need to add the google-services.json to your project in the frontend folder.

You can get it in your firebase dashboard, make sure you follow the setup steps, you can find them in the wiki at https://github.com/SimCoderYoutube/InstagramClone/wiki/Setup-your-project
